### ISSUE TITLE
pieces/渡り鳥のソムニウムがSix Pieces ～多重調教～として表示される

### ISSUE THREAD

**Issue by misaki058x** [ryoha000/launcherg#13]
Whirlpool pieces/渡り鳥のソムニウムがSix Pieces ～多重調教～として扱われている
現状
![image](https://github.com/ryoha000/launcherg/assets/145315228/fbad218f-7c28-4a47-bf4d-ec1269a4f4a0)

**Comment by ryoha000** [comment]
他にもこの話を聞いたので対応します
僕の環境だと`C:\Users\ryoha\Desktop\既プレイゲーム\pieces／渡り鳥のソムニウム.lnk`なんですがどういうパスにありますか？

**Comment by misaki058x** [comment]
自身の環境だと
`W:\others\software\Whirlpool\pieces\pieces.exe`
となっています。
