### ISSUE TITLE
全ゲーを登録したゲームから削除

### ISSUE THREAD

**Issue by Omar-Abdul-Azeez** [ryoha000/launcherg#15]

**Comment by ryoha000** [comment]
### Japanese
英語で issue を作成していただいてOKです
内容は登録したすべてのゲームを消す機能ですか？
UI上に出すのは難しいですがワークアラウンドとして`C:\Users\${UserName}\AppData\Roaming\launcherg\launcherg_sqlite.db3`を削除するとすべてのデータが消去されます

### English
You can create an issue in English.
Is the issue about deleting all registered games?
It is difficult to show on the UI, but if you delete `C:\Users\${UserName}\AppData\Roaming\launcherg\launcherg_sqlite.db3` as a workaround, all data will be deleted.

**Comment by Omar-Abdul-Azeez** [comment]
あっ…そうそう登録したゲームのデータの削除です。なんか誤字してしまいましてすみません。
日本語もOKと言いたいところなんですけれども、おこがましいかもね。(苦笑)

**Comment by ryoha000** [comment]
Q&Aを書きました
機能として提供はしない予定ですがなにかあれば re-open してください
https://ryoha000.hatenablog.com/entry/2023/09/24/003605
